/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ShitPunksNFT } from "./ShitPunksNFT";
export * as factories from "./factories";
export { ShitPunksNFT__factory } from "./factories/ShitPunksNFT__factory";
